---

# The media folder is expected to live one directory up in /webapps/application_name/media
- name: Remove {{ project_path }} contents
  file:
    state: absent
    path: "{{ project_path }}/"
  tags: deploy

- name: Recreate {{ project_path }} directory
  file:
    state: directory
    path: "{{ project_path }}/"
  tags: deploy

- name: Move the django content to the project_path
  command: rsync -r {{ tmp_build.path }}/src/django/ {{ project_path }}/ --exclude test
  tags: deploy

- name: Copy the requirements folder
  command: cp -r {{ tmp_build.path }}/requirements {{ project_path }}/requirements
  tags: deploy

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}
  tags: deploy

- name: Run the Django syncdb command
  django_manage:
    command: syncdb
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_syncdb is defined and run_django_syncdb
  tags:
    - django.syncdb
    - deploy

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags:
    - django.migrate
    - deploy

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_collectstatic is defined and run_django_collectstatic
  notify: restart application
  tags:
    - django.collectstatic
    - deploy
