#!/bin/sh

make isort
if git diff-index --cached --name-only HEAD | grep "src/vue"; then
    make check-linters-front || exit 1
fi

if git diff-index --cached --name-only HEAD | grep "src/django"; then
    make check-linters-back || exit 1
fi
