---

- name: Add project environment variables
  lineinfile:
    path: "../venv/bin/activate"
    state: present
    regexp: ^export {{ item.key }}
    line: export {{ item.key }}='{{ item.value }}'
  loop: "{{ project_environment | dict2items }}"

- name: Set code_version env variable in venv to last commit of current branch
  lineinfile:
    path: "../venv/bin/activate"
    state: present
    regexp: ^export CODE_VERSION=
    line: 'export CODE_VERSION=$(git rev-parse HEAD)'

- name: Check for an existing local backup directory
  local_action:
    module: stat
    path: "{{ local_backup_dir }}"
  register: localbdir

- name: Create local backup dir
  local_action:
    module: file
    path: "{{ local_backup_dir }}"
    state: directory
  when: not localbdir.stat.exists or not localbdir.stat.isdir
