---

- name: Add django env variables
  lineinfile:
    path: "../venv/bin/activate"
    state: present
    regexp: ^export {{ item.key }}
    line: export {{ item.key }}='{{ item.value }}'
  loop: "{{ django_environment | dict2items }}"

- name: Check for an existing local backup directory
  local_action:
    module: stat
    path: "{{ local_backup_dir }}"
  register: localbdir

- name: Create local backup dir
  local_action:
    module: file
    path: "{{ local_backup_dir }}"
    state: directory
  when: not localbdir.stat.exists or not localbdir.stat.isdir
