# Django environment variables.
project_environment:
  BASELINK: "{{ baselink }}"
  API_URL: "{{ api_url }}"
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  DATABASE_HOST: "{{ db_host }}"
  DATABASE_PORT: "{{ db_port }}"
  BROKER_URL: "{{ broker_url }}"
  DEFAULT_LMS_PROFILE_PICTURE: "{{ default_lms_profile_picture }}"
  LTI_SECRET: "{{ lti_secret }}"
  LTI_KEY: "{{ lti_key }}"
  SENTRY_URL: "{{ sentry_url }}"
  SENTRY_AUTH_TOKEN: "{{ sentry_auth_token }}"
  SENTRY_DSN: "{{ sentry_dsn }}"
  SENTRY_ORG: "{{ sentry_org }}"
  SENTRY_PROJECT: "{{ sentry_project }}"
  SENTRY_LOAD_DOTENV: "{{ sentry_load_dotenv }}"
  MAILGUN_API_KEY: "{{ mailgun_api_key }}"
  MAILGUN_SENDER_DOMAIN: "{{ test_mailgun_sender_domain }}"
  RELEASE_VERSION: "{{ release_version }}"
