# Django environment variables.
django_environment:
  BASELINK: "{{ baselink }}"
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  DATABASE_HOST: "{{ db_host }}"
  DATABASE_PORT: "{{ db_port }}"
  BROKER_URL: "{{ broker_url }}"
  LTI_SECRET: "{{ lti_secret }}"
  LTI_KEY: "{{ lti_key }}"
  EMAIL_HOST: "{{ email_host }}"
  EMAIL_HOST_USER: "{{ email_host_user }}"
  EMAIL_HOST_PASSWORD: "{{ email_host_password }}"
