# Generated by Django 2.2.10 on 2020-08-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0047_dynamic_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='files',
        ),
        migrations.AddField(
            model_name='filecontext',
            name='is_comment_file',
            field=models.BooleanField(default=False),
        ),
    ]
