# Generated by Django 2.2.10 on 2020-08-22 21:28

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0048_auto_20200820_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
