# Generated by Django 2.2.10 on 2020-08-23 12:24

import datetime

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0050_auto_20200823_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CITextField(default=datetime.datetime(2020, 8, 23, 12, 24, 22, 251037), max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
