# Generated by Django 2.2.10 on 2020-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0051_auto_20200823_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='names_role_service',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='abbreviation',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
