# Generated by Django 2.2.10 on 2020-08-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0052_auto_20200823_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignments_grades_service',
            field=models.TextField(null=True),
        ),
    ]
