# Generated by Django 2.2.10 on 2020-08-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0053_assignment_assignments_grades_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='needs_lti_link',
        ),
    ]
