# Generated by Django 2.2.10 on 2020-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0054_remove_journal_needs_lti_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='api_client_id',
            field=models.TextField(default='10000000000002'),
        ),
        migrations.AddField(
            model_name='instance',
            name='lti_client_id',
            field=models.TextField(default='10000000000001'),
        ),
    ]
