# Generated by Django 2.2.10 on 2020-09-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0055_auto_20200901_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='api_client_secret',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='api_client_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='lti_client_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
