# Generated by Django 2.2.10 on 2020-08-31 12:45

from django.db import migrations, models

import VLE.models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0057_teacher_entry_setters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='entry',
            field=models.OneToOneField(null=True, on_delete=VLE.models.CASCADE_IF_UNLIMITED_ENTRY_NODE_ELSE_SET_NULL, to='VLE.Entry'),
        ),
    ]
