# Generated by Django 2.2.10 on 2020-09-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0057_instance_lti_deployment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='lti_deployment_id',
            new_name='lti_deployment_ids',
        ),
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
