# Generated by Django 2.2.10 on 2020-09-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0058_conditional_node_cascde_from_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecontext',
            name='course',
        ),
    ]
