# Generated by Django 2.2.10 on 2020-09-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0058_auto_20200903_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='default_lms_profile_picture',
        ),
        migrations.AddField(
            model_name='instance',
            name='lms_name',
            field=models.TextField(choices=[('Canvas', 'Canvas')], null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='lms_url',
            field=models.TextField(null=True),
        ),
    ]
