# Generated by Django 2.2.10 on 2020-09-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0059_auto_20200903_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='lms_name',
            field=models.TextField(blank=True, choices=[(None, None), ('Canvas', 'Canvas')], null=True),
        ),
    ]
