# Generated by Django 2.2.10 on 2020-09-16 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0059_remove_filecontext_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, editable=False, size=None),
        ),
    ]
