# Generated by Django 2.2.10 on 2020-09-15 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0062_preferences_group_only_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='new_journal_import_request_notifications',
            field=models.TextField(choices=[('d', 'd'), ('w', 'w'), ('p', 'p'), ('o', 'o')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('COURSE', 'new_course_notifications'), ('ASSIGNMENT', 'new_assignment_notifications'), ('NODE', 'new_node_notifications'), ('ENTRY', 'new_entry_notifications'), ('GRADE', 'new_grade_notifications'), ('COMMENT', 'new_comment_notifications'), ('JIR', 'new_journal_import_request_notifications'), ('DEADLINE', 'None')], max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='jir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VLE.JournalImportRequest'),
        ),
    ]
