# Generated by Django 2.2.10 on 2020-10-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0064_use_ejournal_default_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetnode',
            name='attached_files',
            field=models.ManyToManyField(related_name='attached_preset_nodes', to='VLE.FileContext'),
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='files',
            new_name='attached_files',
        ),
        migrations.AlterField(
            model_name='comment',
            name='attached_files',
            field=models.ManyToManyField(related_name='attached_comments', to='VLE.FileContext'),
        ),
    ]
