# Generated by Django 2.2.10 on 2020-10-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0064_use_ejournal_default_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='entry',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='grade_set', to='VLE.Entry'),
        ),
    ]
