# Generated by Django 2.2.10 on 2020-10-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0065_entry_grade_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetnode',
            name='attached_files',
            field=models.ManyToManyField(to='VLE.FileContext'),
        ),
    ]
