# Generated by Django 2.2.10 on 2020-11-13 08:48

from django.db import migrations

import VLE.models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0066_presetnode_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['location']},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', VLE.models.UserManagerExtended()),
            ],
        ),
    ]
