# Generated by Django 2.2.10 on 2020-11-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0068_grade_grade_not_none_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='full_names',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='usernames',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='import_requests',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='image',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='unpublished',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='needs_marking',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='needs_lti_link',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='groups',
        ),
    ]
