# Generated by Django 2.2.10 on 2020-12-02 08:23

from django.db import migrations, models


def setDefaultDisplayNames(apps, schema_editor):
    PresetNode = apps.get_model('VLE', 'PresetNode')

    for preset in PresetNode.objects.all().select_related('forced_template'):
        if preset.type == 'd':
            preset.display_name = preset.forced_template.name
        if preset.type == 'p':
            preset.display_name = 'Progress goal'

        preset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0069_remove_journal_computed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetnode',
            name='display_name',
            field=models.TextField(default='BESTONE'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='presetnode',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, display_name=''), name='non_empty_display_name'),
        ),
        migrations.RunPython(setDefaultDisplayNames, reverse_code=lambda apps, schema_editor: None),
    ]
