# Generated by Django 2.2.10 on 2021-02-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0070_presetnode_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='default_lms_profile_picture',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignments_grades_service',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='names_role_service',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='api_client_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='api_client_secret',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='lms_name',
            field=models.TextField(blank=True, choices=[(None, None), ('Canvas', 'Canvas')], null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='lms_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='lti_client_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='lti_deployment_ids',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='abbreviation',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
