# Generated by Django 2.2.19 on 2021-03-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0071_auto_20210202_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sis_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
