# Generated by Django 2.2.10 on 2021-01-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0072_template_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='location',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('location', 'template')},
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, name=''), name='non_empty_name'),
        ),
    ]
