# Generated by Django 2.2.10 on 2021-01-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0073_field_location_constrains_and_non_empty_template_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['name']},
        ),
    ]
