# Generated by Django 2.2.19 on 2021-03-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0073_auto_20210312_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lms_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
