# Generated by Django 2.2.19 on 2021-03-12 21:54

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0074_course_lms_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
