# Generated by Django 2.2.10 on 2021-02-09 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0078_assignment_points_possible_positive_float_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLE.TemplateChain'),
        ),
    ]
