# Generated by Django 2.2.10 on 2021-02-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0079_removed_blank_and_null_from_template_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatechain',
            name='default_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='templatechain',
            constraint=models.CheckConstraint(check=models.Q(('default_grade__gte', 0), ('default_grade__isnull', True), _connector='OR'), name='default_grade_gte_0'),
        ),
    ]
