# Generated by Django 2.2.10 on 2021-02-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0080_default_template_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatechain',
            name='allow_custom_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='templatechain',
            name='title_description',
            field=models.TextField(null=True, blank=True),
        ),
    ]
