# Generated by Django 2.2.10 on 2021-03-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0082_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='hide_past_deadlines_of_assignments',
            field=models.ManyToManyField(related_name='_preferences_hide_past_deadlines_of_assignments_+', to='VLE.Assignment'),
        ),
    ]
