# Generated by Django 2.2.19 on 2021-03-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0083_auto_20210321_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lti_id',
            new_name='lti_1p3_id',
        ),
        migrations.AddField(
            model_name='user',
            name='lti_1p0_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
