# Generated by Django 2.2.19 on 2021-03-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0084_auto_20210321_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='active_lti_id',
            new_name='lti_id',
        ),
    ]
