# Generated by Django 2.2.10 on 2021-04-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0084_multiple_video_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
