# Generated by Django 2.2.10 on 2020-10-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0085_entry_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.TextField(default='Demo'),
        ),
    ]
