# Generated by Django 2.2.19 on 2021-04-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0085_auto_20210327_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
