# Generated by Django 2.2.19 on 2021-05-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0086_better_default_demo_instance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='auto_save_drafts',
            field=models.BooleanField(default=True),
        ),
    ]
