# Generated by Django 2.2.19 on 2021-05-04 18:20

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0086_better_default_demo_instance_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='active_lti_id',
            new_name='lms_id',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='lti_id',
            new_name='lms_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lti_id',
            new_name='lti_1p0_id',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='default_lms_profile_picture',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignments_grades_service',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='lti_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='names_role_service',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='api_client_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='api_client_secret',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='lms_name',
            field=models.TextField(blank=True, choices=[(None, None), ('Canvas', 'Canvas')], null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='lms_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='lti_client_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='lti_deployment_ids',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lti_1p3_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sis_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='abbreviation',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.TextField(default='Demo', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('lms_id', 'course')},
        ),
    ]
