# Generated by Django 2.2.19 on 2021-05-03 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0086_better_default_demo_instance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('score_as_range', models.BooleanField(default=False)),
                ('location', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('h', 'Hidden from students'), ('v', 'Visible to students'), ('huv', 'Hidden from students untill overall feedback is provided')], default='v', max_length=3)),
                ('hide_score_from_students', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='VLE.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('points', models.FloatField()),
                ('initial_feedback', models.TextField(blank=True)),
                ('location', models.PositiveIntegerField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='VLE.Criterion')),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.AddField(
            model_name='criterion',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='VLE.Rubric'),
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, name=''), name='non_empty_name'),
        ),
        migrations.AlterUniqueTogether(
            name='rubric',
            unique_together={('name', 'assignment')},
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.CheckConstraint(check=models.Q(points__gte=0.0), name='points_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, name=''), name='non_empty_name'),
        ),
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('name', 'rubric')},
        ),
    ]
