---

- name: Prompt to ask whether a git tag message should be created?
  pause:
    prompt: Should a git tag message be created (yes/no)?
  register: prompt
- set_fact:
    create_git_tag: "{{ prompt.user_input | bool }}"

- name: Prompt for release git tag message "This update brings X, Y, Z."
  pause:
    prompt: 'Please provide a git tag message "This update brings X, Y, Z."'
  register: git_tag_message
  when: create_git_tag

- set_fact:
    our_date_format: "{{ ansible_date_time.day }}-{{ ansible_date_time.month }}-{{ ansible_date_time.year }}"
  when: create_git_tag

- name: List all local tags
  connection: local
  become: no
  local_action: "command git tag -l"
  register: result
  when: create_git_tag

- name: Clean all local tags
  connection: local
  become: no
  local_action: "command git tag -d {{ item }}"
  with_items: "{{ result.stdout_lines }}"
  when: create_git_tag

- name: Retrieve upstream tags
  connection: local
  become: no
  local_action: "command git fetch --tags"
  when: create_git_tag

- name: Create a new tag on the current branch
  connection: local
  become: no
  local_action:
    "command git tag -a v{{ new_release_version }} -m 'Released: {{ our_date_format }}' -m '{{ git_tag_message.user_input }}'"
  when: create_git_tag
