---

- name: Prompt for new release
  pause:
    prompt: "Do you want to create a new release (yes/no)?"
  register: prompt
- set_fact:
    new_release: "{{ prompt.user_input | bool }}"

- name: Prompt for new version number
  pause:
    prompt: "Release version x.x.x"
  register: prompt
  when: new_release
- set_fact:
    new_release_version: "{{ prompt.user_input }}"
  when: new_release

- name: Assert provided version is higher than known version.
  assert:
    that:
        - new_release_version is version(release_version, operator='>=', strict=True)
    fail_msg: "Provided version is lower than known version"
    success_msg: "Succesfully provided a new version higher or equal to the known version"
  when: new_release
