---

- name: Update package.json version
  become: no
  replace:
    path: "../src/vue/package.json"
    regexp: '^(?P<start>[ ]*"version": "v)\d+.*(?P<end>".*)$'
    replace: '\g<start>{{ new_release_version }}\g<end>'
  delegate_to: localhost

- name: Update confing env/base.yml version
  become: no
  replace:
    path: "../config/env_vars/base.yml"
    regexp: '^(release_version:).*$'
    replace: '\1 {{ new_release_version }}'
  delegate_to: localhost

- name: Update release in venv exports
  become: no
  lineinfile:
    path: "../venv/bin/activate"
    state: present
    regexp: ^export RELEASE_VERSION=
    line: export RELEASE_VERSION='{{ new_release_version }}'
  delegate_to: localhost

- set_fact:
    release_version: "{{ new_release_version }}"
