all:
  children:
    staging:
      vars:
        env: stage
        ansible_ssh_private_key_file: /home/maarten/.ssh/desktop.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_ssh_user: ubuntu
      hosts:
        monitoring-demo.ejournal.app:
          baselink: https://monitoring-demo.ejournal.app
          api_url: https:/api.monitoring-demo.ejournal.app
          mailgun_sender_domain: monitoring-demo.ejournal.app
