<template>
    <b-modal
        ref="bonusPointsModal"
        title="Import bonus points"
        size="lg"
        noEnforceFocus
        @hide="resetErrorLogs()"
    >
        Use the button below to import bonus points from a <i>comma separated value</i> file (.csv).
        This type of file can be easily generated by any spreadsheet application. Use the following
        format:<br/>

        <div class="text-monospace mb-2 full-width text-center">
            username1, bonus1<br/>
            username2, bonus2<br/>
            username3, bonus3<br/>
        </div>

        <b>Note:</b> Importing bonus points for a user will overwrite their current bonus points!

        <b-form-file
            ref="bonusInput"
            v-model="file"
            accept="*/*.csv"
            :state="state"
            :placeholder="placeholderText"
            class="fileinput mb-2"
            @change="fileHandler"
        />
        <b-progress
            v-if="uploading"
            class="mb-2"
        >
            <b-progress-bar
                :value="loaded"
                :max="total"
                :label="progressLabel"
                show-progress
                animated
            />
        </b-progress>

        <b-button
            v-if="!autoUpload"
            slot="modal-footer"
            class="green-button float-right"
            :class="{ 'input-disabled': !file }"
            @click="uploadFile"
        >
            <icon name="upload"/>
            Upload
        </b-button>

        <div v-if="errorLogs">
            <b class="text-red">Errors in file:</b>
            <div
                v-if="errorLogs.non_participants || errorLogs.unknown_users"
                class="text-grey mb-1"
            >
                <i>Note: it is likely that one or more of the users reported as unknown or non participant still need
                    to visit this assignment on the LMS (Canvas).</i>
            </div>
            <b
                v-if="errorLogs.general"
                class="mb-1"
            >
                {{ errorLogs.general }}
            </b>
            <div
                v-if="errorLogs.unknown_users"
                class="mb-1"
            >
                <b>The following users do not exist:</b><br/>
                <span
                    v-for="(username, lineNumber) in errorLogs.unknown_users"
                    :key="`unknown-users-${lineNumber}-${username}`"
                >
                    <b>&emsp;&emsp;&emsp;{{ lineNumber }})</b> {{ username }}<br/>
                </span>
            </div>
            <div
                v-if="errorLogs.non_participants"
                class="mb-1"
            >
                <b>The following users are not participants of the assignment:</b><br/>
                <span
                    v-for="(username, lineNumber) in errorLogs.non_participants"
                    :key="`non_participants-${lineNumber}-${username}`"
                >
                    <b>&emsp;&emsp;&emsp;{{ lineNumber }})</b> {{ username }}<br/>
                </span>
            </div>
            <div
                v-if="errorLogs.incorrect_format_lines"
                class="mb-1"
            >
                <b>The following lines are incorrectly formatted:</b><br/>
                <span
                    v-for="(content, lineNumber) in errorLogs.incorrect_format_lines"
                    :key="`incorrect-format-${lineNumber}-${content}`"
                >
                    <b>&emsp;&emsp;&emsp;{{ lineNumber }})</b> {{ content }}<br/>
                </span>
            </div>
            <div v-if="errorLogs.duplicates">
                <b>The following users occur twice:</b><br/>
                <span
                    v-for="(username, lineNumber) in errorLogs.duplicates"
                    :key="`duplicates-${lineNumber}-${username}`"
                >
                    <b>&emsp;&emsp;&emsp;{{ lineNumber }})</b> {{ username }}<br/>
                </span>
            </div>
        </div>
    </b-modal>
</template>

<script>
import auth from '@/api/auth.js'

export default {
    props: {
        aID: {
            required: true,
            String,
        },
        autoUpload: {
            default: false,
            Boolean,
        },
        endpoint: {
            default: 'users/upload',
        },
        placeholder: {
            default: 'No file chosen',
        },
        contentID: {
            default: null,
        },
    },
    data () {
        return {
            placeholderText: 'No file chosen',
            file: null,
            state: null,
            uploading: false,
            loaded: 0,
            total: 100,
            errorLogs: null,
        }
    },
    computed: {
        progressLabel () {
            if (this.loaded === this.total) {
                return 'Processing...'
            }
            return `${Math.floor((this.loaded / this.total) * 100)}%`
        },
    },
    created () {
        // Assume the given file is present in the backend
        if (this.placeholder !== null && this.placeholder !== 'No file chosen') {
            this.file = true
            this.placeholderText = this.placeholder
        }
    },
    methods: {
        resetUploadState () {
            this.uploading = false
            this.total = 100
            this.progress = 0
        },
        fileHandler (e) {
            const files = e.target.files

            if (!files || !files.length) { return }

            const file = files[0]

            if (file.size > this.$root.maxFileSizeBytes) {
                this.$toasted.error(
                    `The selected file exceeds the maximum file size of ${this.$root.maxFileSizeLabel}.`)
                this.state = false
            } else if (file.name.length > this.$root.maxFileNameLength) {
                this.$toasted.error(
                    `The selected file exceeds the maximum file name length of ${this.$root.maxFileNameLength}.`)
                this.state = false
            } else {
                this.state = true
                this.file = file
                this.resetErrorLogs()

                this.$emit('fileSelect', this.file.name)

                if (this.autoUpload) { this.uploadFile() }
            }
        },
        uploadFile () {
            const formData = new FormData()
            formData.append('file', this.file)
            formData.append('assignment_id', this.aID)
            formData.append('content_id', this.contentID)

            this.uploading = true
            auth.uploadFile(
                this.endpoint,
                formData,
                {
                    onUploadProgress: (e) => {
                        this.loaded = e.loaded
                        this.total = e.total
                    },
                },
                {
                    customSuccessToast: 'Successfully imported bonus points.',
                    customErrorToast: 'Something is wrong with the uploaded file.',
                },
            )
                .then(() => {
                    this.$emit('bonusPointsSuccessfullyUpdated', this.file.name)
                    this.state = null
                })
                .catch((error) => {
                    this.$emit('bonusPointsFileFormatIssues', this.file.name)
                    this.state = false
                    this.errorLogs = error.response.data.description
                })
                .finally(() => {
                    this.resetUploadState()
                    this.file = null
                    this.$refs.bonusInput.reset()
                })
        },
        resetErrorLogs () {
            this.errorLogs = null
        },
        show () {
            this.$refs.bonusPointsModal.show()
        },
        hide () {
            this.$refs.bonusPointsModal.hide()
        },
    },
}
</script>
