---

- name: Ensure postfix is installed.
  package:
    name: postfix
    state: present

- name: Update Postfix configuration.
  lineinfile:
    dest: /etc/postfix/main.cf
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }} ="
  with_items:
    - name: inet_interfaces
      value: localhost
    - name: inet_protocols
      value: all
    - name: smtpd_tls_security_level
      value: may
    - name: smtp_tls_security_level
      value: may
    - name: smtp_tls_loglevel
      value: 1
    - name: smtpd_tls_loglevel
      value: 1
  notify: restart postfix

- name: Set mailname to {{ inventory_hostname }}
  template:
    mode: "u=rw,g=r,o=r"
    src: mailname.j2
    dest: /etc/mailname
  notify: restart postfix

- name: Ensure postfix is started and enabled at boot.
  service:
    name: postfix
    state: started
    enabled: true

- name: Install logwatch
  apt:
    name: logwatch
    state: present

- name: Configure logwatch
  template:
    src: logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
