name: eJournal CI
on: push

jobs:
  backend-tests:
    name: Run Django Tests
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.6.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
      - name: Install dependencies
        run: pip3 install -r requirements/ci.txt
      - name: Run tests
        run: pytest -c /dev/null src/django/test -k test_generic_test_utils_equal_models
        env:
          BASELINK: 'http://localhost:8080'
          DJANGO_SECRET_KEY: '@a4c3cpgfe0@8s!be=23d5+3e30vyj7!q%tolqpewafp^-@=br'
          DATABASE_NAME: postgres
          DATABASE_USER: postgres
          DATABASE_PASSWORD: password
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          BROKER_URL: 'amqp://postgres:password@localhost/postgres'
          DEFAULT_LMS_PROFILE_PICTURE: 'images/messages/avatar-50.png'
          LTI_SECRET: 4339900ae5861f3086861ea492772864
          LTI_KEY: 0cd500938a8e7414ccd31899710c98ce
          DJANGO_SETTINGS_MODULE: 'VLE.settings.travis'
          SENTRY_DSN: 'https://dummydsn@sentry.io/000001'
          SENTRY_SENTRY_ORG: ejournal
          SENTRY_PROJECT: ejournal
          MAILGUN_API_KEY: placeholder
          MAILGUN_SENDER_DOMAIN: placeholder
          API_URL: 'http://localhost:8000'
          RELEASE_VERSION: '1.0.0'
          CODE_VERSION: 937aa7be86b36e1d30444336c073bbf6a4e72b2f
