name: eJournal CI
on: push

jobs:
  test:
    env:
      BASELINK="http://localhost:8080"
      DJANGO_SECRET_KEY="@a4c3cpgfe0@8s!be=23d5+3e30vyj7!q%tolqpewafp^-@=br"
      DATABASE_NAME="ejournal"
      DATABASE_USER="ejournal"
      DATABASE_PASSWORD="password"
      DATABASE_HOST="localhost"
      DATABASE_PORT="5432"
      BROKER_URL="amqp://ejournal:password@localhost/ejournal"
      DEFAULT_LMS_PROFILE_PICTURE="images/messages/avatar-50.png"
      LTI_SECRET="4339900ae5861f3086861ea492772864"
      LTI_KEY="0cd500938a8e7414ccd31899710c98ce"
      DJANGO_SETTINGS_MODULE="VLE.settings.travis"
      SENTRY_DSN="https://dummydsn@sentry.io/000001"
      SENTRY_SENTRY_ORG="ejournal"
      SENTRY_PROJECT="ejournal"
      MAILGUN_API_KEY="placeholder"
      MAILGUN_SENDER_DOMAIN="placeholder"
      API_URL="http://localhost:8000"
      RELEASE_VERSION="1.0.0"
      CODE_VERSION="937aa7be86b36e1d30444336c073bbf6a4e72b2f"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12.5'
      - name: Setup
        run: make setup-ci
      - name: Test
        run: make test
      - uses: codecov/codecov-action@v1
